// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Garage2._0.Migrations
{
    [DbContext(typeof(_1))]
    [Migration("20260702142235_Init")]
    partial class Init
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.9");

            modelBuilder.Entity("Garage2._0.Models.ParkedVehicle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("arrivalTime")
                        .HasColumnType("TEXT");

                    b.Property<short>("color")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("departureTime")
                        .HasColumnType("TEXT");

                    b.Property<string>("registrationNumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("vehicleBrand")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("vehicleModel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("vehicleType")
                        .HasColumnType("INTEGER");

                    b.Property<int>("wheels")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("ParkedVehicle");
                });
#pragma warning restore 612, 618
        }
    }
}
